import type { ConceptSeed } from './types';

export const conceptSeeds: ConceptSeed[] = [
  // --- API design ----------------------------------------------------------
  {
    slug: 'http-request-lifecycle',
    title: 'HTTP request lifecycle',
    category: 'api-design',
    difficulty: 'beginner',
    status: 'mastered',
    importance: 'high',
    summary:
      'What actually happens between a client sending a request and your handler returning a response.',
    mentalModel:
      'A request is a structured message (method, path, headers, body) that travels through layers — DNS, TLS, load balancer, framework router, middleware, handler — and a response travels back. Each layer can short-circuit, transform, or observe it.',
    howItWorks:
      'DNS resolves the host, TLS establishes an encrypted channel, the edge/load balancer routes to an instance, the framework parses the request and runs middleware (auth, logging, rate limiting), the handler executes business logic, and the response is serialized and sent back with a status code and headers.',
    whenToUse:
      'Always — understanding the lifecycle tells you where to enforce auth, where to cache, where latency comes from, and where to add observability.',
    whenNotToUse: '',
    commonMistakes:
      'Treating the framework handler as the whole story and ignoring edge/proxy behavior; forgetting that headers and status codes are part of the API contract.',
    tradeoffs:
      'Doing work at the edge is fast but limited; doing it in the handler is flexible but slower and closer to your database.',
    realWorldExamples:
      'A Next.js route handler on Vercel: request hits Vercel edge, routes to a serverless function, runs your code, queries Neon, returns JSON.',
    related: ['rest-api-design', 'rate-limiting', 'serverless-functions'],
    tags: ['http', 'fundamentals'],
  },
  {
    slug: 'rest-api-design',
    title: 'REST API design',
    category: 'api-design',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'high',
    summary:
      'Designing resource-oriented HTTP APIs with predictable methods, status codes, and shapes.',
    mentalModel:
      'Model nouns (resources) and use HTTP verbs as the actions. The URL identifies the thing; the method says what to do to it.',
    howItWorks:
      'Resources get stable URLs (/invoices/:id). GET reads, POST creates, PUT/PATCH update, DELETE removes. Status codes communicate outcome (2xx success, 4xx client error, 5xx server error). Responses are consistent JSON envelopes.',
    whenToUse:
      'CRUD-heavy products, public APIs, and anything where caching and tooling benefit from HTTP semantics.',
    whenNotToUse:
      'Highly relational client needs (consider GraphQL) or internal service-to-service calls where RPC is simpler.',
    commonMistakes:
      'Verbs in URLs (/getInvoice), inconsistent error shapes, 200 OK with an error body, and leaking database structure directly as the API.',
    tradeoffs:
      'REST is universally understood and cache-friendly, but can require many round-trips for nested data.',
    realWorldExamples: 'Stripe and GitHub REST APIs are canonical references.',
    related: ['api-validation', 'api-error-handling', 'pagination', 'http-request-lifecycle'],
    tags: ['rest', 'api'],
  },
  {
    slug: 'api-validation',
    title: 'API validation',
    category: 'api-design',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'high',
    summary:
      'Rejecting malformed input at the boundary so the rest of your code can trust its data.',
    mentalModel:
      'Validation is a gate at the edge of your system. Inside the gate, types are guarantees, not hopes.',
    howItWorks:
      'Parse the incoming body/query/params against a schema (e.g. Zod). On failure, return 400 with field-level errors. On success, pass a typed object downstream.',
    whenToUse: 'Every external input: request bodies, query params, webhooks, file uploads.',
    whenNotToUse: 'Trusted, already-validated internal data (avoid re-validating in hot loops).',
    commonMistakes:
      'Validating in the UI only, trusting client-sent IDs, and coercing silently instead of rejecting.',
    tradeoffs: 'Strict schemas catch bugs early but add friction when shapes evolve.',
    realWorldExamples:
      'Zod schema on a Next.js route handler producing typed input and a 400 response on failure.',
    related: ['rest-api-design', 'api-error-handling'],
    prerequisites: ['rest-api-design'],
    tags: ['validation', 'zod'],
  },
  {
    slug: 'api-error-handling',
    title: 'API error handling',
    category: 'api-design',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'high',
    summary:
      'A consistent convention for representing, logging, and returning errors across an API.',
    mentalModel:
      'Errors are part of your API contract. Clients should be able to branch on a stable error code, not parse human messages.',
    howItWorks:
      'Define an error envelope ({ error: { code, message, details } }), map exceptions to status codes centrally, log with context, and never leak stack traces or secrets to clients.',
    whenToUse: 'Every API. Establish the convention before you have 50 endpoints.',
    whenNotToUse: '',
    commonMistakes:
      'Returning 200 with an error body, inconsistent shapes per route, swallowing errors, and exposing internal messages.',
    tradeoffs:
      'A rich error taxonomy helps clients but is more to maintain; too granular and it becomes noise.',
    realWorldExamples: 'Stripe error objects with type/code/param fields.',
    related: ['rest-api-design', 'api-validation', 'observability'],
    tags: ['errors', 'api'],
  },
  {
    slug: 'pagination',
    title: 'Pagination',
    category: 'api-design',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'high',
    summary: 'Returning large result sets in stable, performant pages.',
    mentalModel:
      'Offset pagination is "skip N, take M" — simple but drifts and slows on deep pages. Cursor pagination is "give me items after this opaque marker" — stable and fast.',
    howItWorks:
      'Cursor pagination encodes the sort key of the last seen row (e.g. created_at + id) into an opaque cursor. The next query filters WHERE (created_at, id) < (cursor) ORDER BY ... LIMIT M, using an index.',
    whenToUse:
      'Infinite scroll, large/append-heavy lists, and anywhere consistency under inserts matters — prefer cursors.',
    whenNotToUse:
      'Small, bounded lists or admin tables needing "jump to page 7" — offset is fine there.',
    commonMistakes:
      'Deep OFFSET on big tables (full scans), unstable sort keys causing duplicates/skips, and exposing raw DB offsets as cursors.',
    tradeoffs: 'Cursors are fast and stable but cannot random-access pages.',
    realWorldExamples: 'GitHub and Stripe use cursor-based pagination on list endpoints.',
    related: ['rest-api-design', 'postgresql-indexing'],
    prerequisites: ['postgresql-indexing'],
    tags: ['pagination', 'cursor'],
  },

  // --- Auth & security -----------------------------------------------------
  {
    slug: 'authentication',
    title: 'Authentication',
    category: 'auth',
    difficulty: 'intermediate',
    status: 'understood',
    importance: 'critical',
    summary: 'Proving who a request is coming from.',
    mentalModel: 'Authentication answers "who are you?" — distinct from authorization ("what may you do?").',
    howItWorks:
      'A user proves identity (password, OAuth, magic link), the server issues a credential (session cookie or token), and subsequent requests carry that credential which the server verifies.',
    whenToUse: 'Any app with user-specific data.',
    whenNotToUse: 'Truly public, read-only content.',
    commonMistakes:
      'Confusing authn with authz, storing passwords without strong hashing, and putting sensitive data in JWTs.',
    tradeoffs: 'Sessions are easy to revoke; tokens scale statelessly but are hard to revoke.',
    realWorldExamples: 'BetterAuth issuing a session cookie after a magic-link login.',
    related: ['authorization', 'session-based-auth', 'jwt'],
    tags: ['auth', 'security'],
  },
  {
    slug: 'authorization',
    title: 'Authorization',
    category: 'auth',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'critical',
    summary: 'Deciding what an authenticated principal is allowed to do.',
    mentalModel:
      'Every data access should answer "is this actor allowed to touch this specific row?" — not just "are they logged in?".',
    howItWorks:
      'Model roles/permissions or policies; enforce checks at the data layer (e.g. always scope queries by tenant/owner). Prefer "deny by default".',
    whenToUse: 'Every multi-user or multi-tenant system.',
    whenNotToUse: '',
    commonMistakes:
      'Checking auth in the UI only, IDOR (trusting client-supplied IDs), and scattering checks instead of centralizing.',
    tradeoffs: 'Fine-grained policies are powerful but complex; coarse roles are simple but blunt.',
    realWorldExamples: 'Row-level tenant scoping in a B2B SaaS; RBAC in an admin panel.',
    related: ['authentication', 'multi-tenancy', 'security'],
    prerequisites: ['authentication'],
    tags: ['authz', 'security'],
  },
  {
    slug: 'session-based-auth',
    title: 'Session-based auth',
    category: 'auth',
    difficulty: 'intermediate',
    status: 'understood',
    importance: 'medium',
    summary: 'Server-side sessions referenced by an opaque cookie.',
    mentalModel: 'The cookie is just a pointer; the real state lives server-side and can be revoked instantly.',
    howItWorks:
      'On login the server stores a session record and sets an HttpOnly, Secure, SameSite cookie holding the session id. Each request looks up the session.',
    whenToUse: 'Web apps where instant revocation and simplicity matter.',
    whenNotToUse: 'Stateless multi-service APIs where a shared session store is a bottleneck.',
    commonMistakes: 'Non-HttpOnly cookies, missing SameSite, and unbounded session growth.',
    tradeoffs: 'Easy revocation vs. a session store lookup on every request.',
    realWorldExamples: 'Classic web app sessions backed by Postgres or Redis.',
    related: ['authentication', 'jwt'],
    tags: ['session', 'cookies'],
  },
  {
    slug: 'jwt',
    title: 'JWT',
    category: 'auth',
    difficulty: 'intermediate',
    status: 'reading',
    importance: 'medium',
    summary: 'Signed, self-contained tokens carrying claims.',
    mentalModel: 'A JWT is a tamper-evident note the server signs and trusts later without a lookup.',
    howItWorks:
      'The server signs a payload (claims + expiry). Clients send it as a Bearer token; the server verifies the signature and reads claims without hitting a store.',
    whenToUse: 'Stateless service-to-service auth, short-lived access tokens.',
    whenNotToUse: 'When you need instant revocation or store lots of mutable state.',
    commonMistakes:
      'Long-lived tokens with no revocation, putting secrets/PII in claims, and accepting alg:none.',
    tradeoffs: 'No lookup (fast, scalable) vs. hard to revoke before expiry.',
    realWorldExamples: 'Short-lived access token + refresh token rotation.',
    related: ['session-based-auth', 'authentication'],
    tags: ['jwt', 'tokens'],
  },
  {
    slug: 'security',
    title: 'API & application security',
    category: 'security',
    difficulty: 'advanced',
    status: 'needs-review',
    importance: 'critical',
    summary: 'The practices that keep data and access safe across the stack.',
    mentalModel: 'Assume every input is hostile and every secret will eventually leak if mishandled.',
    howItWorks:
      'Validate input, scope every query by owner/tenant, store secrets in a vault, encrypt sensitive data, rate-limit, and log access. Defense in depth, deny by default.',
    whenToUse: 'Always; especially before handling money, PII, or multi-tenant data.',
    whenNotToUse: '',
    commonMistakes: 'IDOR, secrets in code/env logs, missing tenant scoping, and verbose error leakage.',
    tradeoffs: 'Stronger controls add friction; the cost of a breach dwarfs it.',
    realWorldExamples: 'Encrypted env-var vault (EnvVault) with per-tenant isolation.',
    related: ['authorization', 'multi-tenancy', 'rate-limiting', 'audit-logs'],
    tags: ['security', 'secrets'],
  },
  {
    slug: 'audit-logs',
    title: 'Audit logs',
    category: 'security',
    difficulty: 'intermediate',
    status: 'reading',
    importance: 'medium',
    summary: 'Immutable records of who did what, when, to which resource.',
    mentalModel: 'An append-only ledger of consequential actions — distinct from debug logging.',
    howItWorks:
      'On state-changing actions, write a structured record (actor, action, target, before/after, timestamp) to an append-only store. Never let app code update or delete entries.',
    whenToUse: 'B2B SaaS, anything with compliance needs, sensitive admin actions.',
    whenNotToUse: 'Trivial read traffic; that is metrics/logging, not audit.',
    commonMistakes: 'Mutable audit tables, missing actor context, and logging secrets.',
    tradeoffs: 'Completeness and immutability vs. storage growth.',
    realWorldExamples: 'A "security & activity" tab showing who changed billing settings.',
    related: ['security', 'observability', 'multi-tenancy'],
    tags: ['audit', 'compliance'],
  },

  // --- Rate limiting & idempotency ----------------------------------------
  {
    slug: 'rate-limiting',
    title: 'Rate limiting',
    category: 'rate-limiting',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'critical',
    summary:
      'Capping how many requests a client can make in a window to protect resources and ensure fairness.',
    mentalModel:
      'A rate limiter is a turnstile. Each request asks "may I pass right now?" and the limiter answers from a small piece of per-key state (counter, timestamps, or tokens).',
    howItWorks:
      'Common algorithms:\n\n- **Fixed window**: count requests per key per time bucket; simple but allows bursts at window edges.\n- **Sliding window**: weight the previous window to smooth edge bursts.\n- **Token bucket**: refill tokens at a steady rate up to a cap; allows controlled bursts, great for APIs.\n- **Leaky bucket**: process at a constant rate, queue or drop overflow.\n\nState lives in a fast store (Redis) keyed by user/IP/API-key, often with atomic Lua scripts to avoid races.',
    whenToUse:
      'Public APIs, auth/login endpoints (brute-force defense), expensive operations, webhook receivers, and any shared resource you must protect from a noisy neighbor.',
    whenNotToUse:
      'Internal, trusted, low-volume calls; or when a queue with backpressure is the better tool for smoothing load.',
    commonMistakes:
      'Storing counters in per-instance memory (breaks across serverless instances), non-atomic read-modify-write causing overcounts, limiting by IP behind a proxy without trusting X-Forwarded-For, and not returning Retry-After / X-RateLimit headers.',
    tradeoffs:
      'Strict limits protect the system but frustrate legitimate bursts; token bucket balances both. Centralized state (Redis) adds a dependency and latency but is correct across instances.',
    realWorldExamples:
      'Stripe and GitHub return X-RateLimit-* headers; login endpoints throttle by IP + account; a webhook receiver token-buckets per source.',
    related: ['caching', 'queues', 'backpressure', 'api-error-handling'],
    prerequisites: ['http-request-lifecycle'],
    tags: ['rate-limit', 'redis', 'resilience'],
  },
  {
    slug: 'idempotency',
    title: 'Idempotency',
    category: 'api-design',
    difficulty: 'advanced',
    status: 'needs-review',
    importance: 'critical',
    summary:
      'Making an operation safe to retry: running it twice has the same effect as running it once.',
    mentalModel:
      'Networks lie. Clients and queues will retry. Design the write so a duplicate is a no-op, not a double charge.',
    howItWorks:
      'The client sends an Idempotency-Key. The server records the key with the result the first time it succeeds inside the same transaction as the effect. A repeat with the same key returns the stored result instead of re-doing the work. Natural idempotency (upserts, set-don’t-increment) is even better.',
    whenToUse:
      'Payments, webhook handlers, queue consumers, "create" endpoints triggered by flaky clients — anywhere a retry could duplicate an effect.',
    whenNotToUse:
      'Pure reads, or naturally idempotent updates where a key adds no value.',
    commonMistakes:
      'Storing the idempotency key in a separate transaction from the effect (a crash between them breaks the guarantee), keying on request time instead of a stable client key, and unbounded key storage.',
    tradeoffs:
      'You trade a little storage and write complexity for correctness under retries — almost always worth it for money or external effects.',
    realWorldExamples:
      'Stripe’s Idempotency-Key header; a Stripe webhook handler that records event.id before acting.',
    related: ['webhooks', 'retry-strategy', 'transactions', 'queues'],
    prerequisites: ['transactions'],
    tags: ['idempotency', 'reliability', 'payments'],
  },

  // --- Webhooks, jobs, queues ---------------------------------------------
  {
    slug: 'webhooks',
    title: 'Webhooks',
    category: 'api-design',
    difficulty: 'advanced',
    status: 'practicing',
    importance: 'critical',
    summary:
      'Receiving server-to-server event notifications instead of polling for changes.',
    mentalModel:
      'A webhook is an inbound event you do not control the timing, ordering, or count of. Treat the endpoint as an untrusted, at-least-once event source.',
    howItWorks:
      'A provider POSTs a signed payload to your URL on an event. You verify the signature, return 2xx fast (acknowledging receipt), and process asynchronously. You dedupe by event id (idempotency) because delivery is at-least-once and can arrive out of order.',
    whenToUse:
      'Reacting to external events: payment succeeded, PR merged, file processed, subscription changed.',
    whenNotToUse:
      'When you need a synchronous answer, or for internal events better served by a queue.',
    commonMistakes:
      'Skipping signature verification, doing heavy work before returning 2xx (causing provider retries/timeouts), assuming exactly-once and ordered delivery, and not being idempotent.',
    tradeoffs:
      'Push (webhooks) is timely and efficient but you must handle retries, ordering, and security; polling is simpler but laggy and wasteful.',
    realWorldExamples:
      'Stripe webhooks (verify signature, store event.id, enqueue work); GitHub webhooks for PR events (MergeAttest).',
    related: ['idempotency', 'queues', 'retry-strategy', 'background-jobs'],
    prerequisites: ['idempotency'],
    tags: ['webhooks', 'events', 'integrations'],
  },
  {
    slug: 'background-jobs',
    title: 'Background jobs',
    category: 'background-jobs',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'high',
    summary: 'Moving slow or unreliable work out of the request path.',
    mentalModel:
      'If the user does not need the result right now, do not make them wait for it. Acknowledge fast, work later.',
    howItWorks:
      'Enqueue a job describing the work, return to the user, and have a worker process the queue with retries and visibility into failures. Jobs must be idempotent because they can run more than once.',
    whenToUse:
      'Email/notifications, image/file processing, third-party API calls, report generation, anything slow or flaky.',
    whenNotToUse: 'Work the user must see the result of synchronously.',
    commonMistakes:
      'Running long tasks inside a serverless request (timeouts), non-idempotent jobs, and no dead-letter handling.',
    tradeoffs: 'Async improves latency and resilience but adds a queue, a worker, and eventual consistency.',
    realWorldExamples: 'DueKind sending reminder emails via a queued worker rather than in the request.',
    related: ['queues', 'cron-jobs', 'retry-strategy', 'dead-letter-queue', 'idempotency'],
    prerequisites: ['queues'],
    tags: ['jobs', 'async', 'workers'],
  },
  {
    slug: 'cron-jobs',
    title: 'Cron jobs',
    category: 'background-jobs',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'medium',
    summary: 'Time-triggered work that runs on a schedule.',
    mentalModel: 'Cron answers "do this every N" — it is a clock, not a queue.',
    howItWorks:
      'A scheduler fires on a cron expression and either does the work directly or, better, enqueues jobs. Must handle overlapping runs and missed ticks.',
    whenToUse: 'Daily digests, cleanup, polling external systems, recurring reminders.',
    whenNotToUse: 'Event-driven reactions (use webhooks/queues) or sub-minute precision needs.',
    commonMistakes: 'Long work directly in the cron tick, overlapping runs, and assuming exactly-once firing.',
    tradeoffs: 'Simple scheduling vs. coarse timing and clustering at tick boundaries.',
    realWorldExamples: 'Vercel Cron triggering a daily "find due reminders" function that enqueues sends.',
    related: ['background-jobs', 'queues'],
    tags: ['cron', 'scheduling'],
  },
  {
    slug: 'queues',
    title: 'Queues',
    category: 'queue',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'critical',
    summary:
      'A durable buffer between producers and consumers that decouples and smooths load.',
    mentalModel:
      'A queue is a shock absorber. Producers drop work in; consumers pull it out at their own pace. Spikes become depth, not failures.',
    howItWorks:
      'Producers enqueue messages; a broker persists them; consumers pull, process, and acknowledge. Unacked messages become visible again (at-least-once delivery), so consumers must be idempotent. Failed messages eventually route to a dead-letter queue.',
    whenToUse:
      'Decoupling services, smoothing bursts, retrying flaky work, fan-out, and any slow task you can do asynchronously.',
    whenNotToUse:
      'When the caller needs a synchronous result, or volume is so low a direct call is simpler.',
    commonMistakes:
      'Assuming exactly-once delivery, non-idempotent consumers, no DLQ, and unbounded retries that poison the queue.',
    tradeoffs:
      'Decoupling and resilience vs. eventual consistency, ordering caveats, and operational overhead.',
    realWorldExamples:
      'SQS/Cloud Tasks for email sends; BurnCap buffering usage events before aggregation.',
    related: ['background-jobs', 'dead-letter-queue', 'retry-strategy', 'idempotency', 'backpressure'],
    tags: ['queue', 'async', 'messaging'],
  },
  {
    slug: 'retry-strategy',
    title: 'Retry strategy',
    category: 'reliability',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'high',
    summary: 'Retrying failed operations without amplifying outages.',
    mentalModel:
      'Naive retries turn a blip into a stampede. Good retries back off, add jitter, cap attempts, and only retry what is safe.',
    howItWorks:
      'Retry transient errors (timeouts, 5xx, 429) with exponential backoff + jitter, a max attempt count, and a budget. Pair with idempotency so retries are safe. Give up to a dead-letter queue.',
    whenToUse: 'Network calls, third-party APIs, queue consumers, database deadlocks.',
    whenNotToUse: 'Non-idempotent operations without an idempotency key, or 4xx client errors.',
    commonMistakes:
      'Retrying everything (including 400s), no jitter (synchronized retries), unbounded attempts, and retrying non-idempotent writes.',
    tradeoffs: 'Resilience to transient failures vs. risk of overload and duplicate effects.',
    realWorldExamples: 'Exponential backoff with full jitter when calling a payment provider.',
    related: ['idempotency', 'queues', 'dead-letter-queue', 'circuit-breaker', 'backpressure'],
    prerequisites: ['idempotency'],
    tags: ['retry', 'backoff', 'resilience'],
  },
  {
    slug: 'dead-letter-queue',
    title: 'Dead letter queue',
    category: 'queue',
    difficulty: 'intermediate',
    status: 'reading',
    importance: 'high',
    summary: 'A holding area for messages that repeatedly fail processing.',
    mentalModel: 'A DLQ is the "ER triage" for poison messages so one bad message cannot block the whole queue.',
    howItWorks:
      'After N failed attempts, the broker moves a message to a separate queue. Humans/alerts inspect it, fix the cause, and optionally replay it.',
    whenToUse: 'Any production queue or webhook pipeline.',
    whenNotToUse: 'Trivial in-process work with no durability needs.',
    commonMistakes: 'No DLQ (poison messages loop forever), no alerting on DLQ depth, and silently dropping failures.',
    tradeoffs: 'Isolation of failures vs. extra plumbing and a backlog you must actually monitor.',
    realWorldExamples: 'SQS redrive policy moving failed jobs to a DLQ after 5 attempts, with an alarm on depth > 0.',
    related: ['queues', 'retry-strategy', 'observability'],
    prerequisites: ['queues'],
    tags: ['dlq', 'queue', 'resilience'],
  },

  // --- Caching -------------------------------------------------------------
  {
    slug: 'caching',
    title: 'Caching',
    category: 'caching',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'critical',
    summary:
      'Storing the result of expensive work closer to where it is read to cut latency and load.',
    mentalModel:
      'A cache is a bet that the same answer will be asked again before it changes. The hard part is not caching — it is knowing when the answer changed.',
    howItWorks:
      'Read-through: check cache, on miss compute and store with a TTL. Layers stack: in-memory, Redis, CDN, browser. Each layer trades freshness for speed. Patterns: cache-aside, write-through, write-behind.',
    whenToUse:
      'Hot reads that are expensive and tolerably stale: config, computed dashboards, rendered pages, reference data.',
    whenNotToUse:
      'Data that must be perfectly fresh (balances mid-transaction), or low-traffic data where the cache never warms.',
    commonMistakes:
      'No invalidation plan, caching per-user data globally, unbounded keys, and stampedes when a hot key expires.',
    tradeoffs:
      'Massive latency/cost wins vs. stale reads and a whole new consistency problem (invalidation).',
    realWorldExamples:
      'CDN caching public pages; Redis caching a computed plan summary in SmartTrips with a short TTL.',
    related: ['cache-invalidation', 'cdn', 'edge-functions', 'rate-limiting'],
    tags: ['cache', 'performance', 'redis'],
  },
  {
    slug: 'cache-invalidation',
    title: 'Cache invalidation',
    category: 'caching',
    difficulty: 'advanced',
    status: 'needs-review',
    importance: 'high',
    summary: 'Keeping cached data correct when the source of truth changes.',
    mentalModel: 'The cache is a lie you tell on purpose. Invalidation is admitting when the lie expired.',
    howItWorks:
      'Strategies: TTL (expire after N seconds), write-through (update cache on write), explicit purge/tag invalidation on mutation, and versioned keys. Choose based on how stale you can tolerate.',
    whenToUse: 'Whenever you cache mutable data.',
    whenNotToUse: 'Immutable/content-addressed data (no invalidation needed — change the key).',
    commonMistakes:
      'Relying on TTL alone for data that must be fresh, forgetting to invalidate related keys, and cache stampedes on expiry.',
    tradeoffs: 'Short TTL = fresher but more misses; explicit invalidation = fresh but coupling and complexity.',
    realWorldExamples: 'Next.js revalidateTag/updateTag on mutation; versioned cache keys per entity.',
    related: ['caching', 'cdn'],
    prerequisites: ['caching'],
    tags: ['invalidation', 'ttl', 'consistency'],
  },
  {
    slug: 'cdn',
    title: 'CDN',
    category: 'caching',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'medium',
    summary: 'A globally distributed cache that serves content near the user.',
    mentalModel: 'Move bytes to the edge so the round-trip is short.',
    howItWorks:
      'Edge nodes cache responses keyed by URL + headers, honoring Cache-Control. Misses fall back to origin and populate the edge.',
    whenToUse: 'Static assets, images, public pages, and cacheable API responses.',
    whenNotToUse: 'Highly personalized or rapidly changing per-user data.',
    commonMistakes: 'Caching personalized responses publicly, wrong Cache-Control, and no purge on deploy.',
    tradeoffs: 'Latency and origin-offload vs. invalidation complexity at the edge.',
    realWorldExamples: 'Vercel/Cloudflare edge caching static pages and assets.',
    related: ['caching', 'edge-functions'],
    tags: ['cdn', 'edge'],
  },

  // --- Serverless ----------------------------------------------------------
  {
    slug: 'edge-functions',
    title: 'Edge functions',
    category: 'serverless',
    difficulty: 'intermediate',
    status: 'reading',
    importance: 'medium',
    summary: 'Code that runs at CDN edge locations close to users.',
    mentalModel: 'A tiny, fast function near the user — great for routing/auth checks, bad for heavy DB work.',
    howItWorks:
      'Runs on a constrained runtime (Web APIs, no full Node) at many locations. Low latency to the user, high latency to a single-region database.',
    whenToUse: 'Redirects, A/B routing, light auth, geolocation, header rewrites.',
    whenNotToUse: 'Heavy database access or Node-only libraries.',
    commonMistakes: 'Querying a single-region DB from the edge, assuming full Node APIs.',
    tradeoffs: 'Proximity to user vs. distance to data and runtime limits.',
    realWorldExamples: 'Edge middleware doing auth redirects before a request hits the function.',
    related: ['serverless-functions', 'cdn', 'caching'],
    tags: ['edge', 'serverless'],
  },
  {
    slug: 'serverless-functions',
    title: 'Serverless functions',
    category: 'serverless',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'high',
    summary: 'On-demand, auto-scaling compute with no server management.',
    mentalModel: 'You ship a function; the platform runs N copies on demand and bills per use. Statelessness is mandatory.',
    howItWorks:
      'A request spins up (or reuses) an instance, runs your handler, and may freeze/die afterward. No shared memory across instances; state must be external.',
    whenToUse: 'Spiky/unpredictable traffic, request-scoped work, small teams avoiding ops.',
    whenNotToUse: 'Long-running tasks, websockets, heavy per-instance caches, or sustained high throughput where cost flips.',
    commonMistakes:
      'In-memory rate limiters/caches, long tasks hitting timeouts, and exhausting DB connections without pooling.',
    tradeoffs: 'Zero ops and elastic scale vs. cold starts, time limits, and statelessness constraints.',
    realWorldExamples: 'Next.js route handlers on Vercel backed by Neon.',
    related: ['cold-starts', 'connection-pooling', 'edge-functions', 'background-jobs'],
    tags: ['serverless', 'vercel'],
  },
  {
    slug: 'cold-starts',
    title: 'Cold starts',
    category: 'serverless',
    difficulty: 'intermediate',
    status: 'reading',
    importance: 'medium',
    summary: 'The latency penalty of booting a fresh function instance.',
    mentalModel: 'A cold instance must boot before it can answer — the first request pays the bill.',
    howItWorks:
      'When no warm instance exists, the platform initializes the runtime and your module. Large dependencies and heavy top-level code make this worse.',
    whenToUse: 'Understand it whenever latency-sensitive endpoints run serverless.',
    whenNotToUse: '',
    commonMistakes: 'Heavy top-level imports, large bundles, and per-request client construction.',
    tradeoffs: 'Scale-to-zero cost savings vs. tail latency on cold paths.',
    realWorldExamples: 'A rarely hit endpoint feeling slow on the first call after idle.',
    related: ['serverless-functions', 'connection-pooling'],
    tags: ['cold-start', 'latency'],
  },
  {
    slug: 'connection-pooling',
    title: 'Connection pooling',
    category: 'database',
    difficulty: 'intermediate',
    status: 'understood',
    importance: 'high',
    summary: 'Reusing a bounded set of database connections instead of opening one per request.',
    mentalModel: 'Connections are expensive and finite. A pool is a shared bag of them; serverless can drain it instantly.',
    howItWorks:
      'A pooler keeps warm connections and hands them out. In serverless, many instances each wanting connections can exceed Postgres limits — use a serverless pooler (PgBouncer/Neon pooler).',
    whenToUse: 'Always with Postgres; especially serverless.',
    whenNotToUse: '',
    commonMistakes: 'New client per request, ignoring max connections, and not using the pooled connection string on Neon.',
    tradeoffs: 'Throughput and stability vs. a pooler dependency and transaction-mode caveats.',
    realWorldExamples: 'Using Neon’s pooled endpoint from Vercel functions.',
    related: ['serverless-functions', 'transactions', 'cold-starts'],
    tags: ['pooling', 'postgres', 'neon'],
  },

  // --- Database ------------------------------------------------------------
  {
    slug: 'postgresql-indexing',
    title: 'PostgreSQL indexing',
    category: 'database',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'high',
    summary: 'Data structures that let the database find rows without scanning the whole table.',
    mentalModel: 'An index is a book’s index — it trades write cost and storage for fast lookups on specific columns.',
    howItWorks:
      'B-tree indexes accelerate equality and range queries and ORDER BY on the indexed columns. Composite indexes follow a left-to-right prefix rule. EXPLAIN ANALYZE shows whether an index is used. Indexes slow writes and use space.',
    whenToUse: 'Columns in WHERE, JOIN, ORDER BY; foreign keys; cursor-pagination sort keys.',
    whenNotToUse: 'Tiny tables, low-selectivity columns, and write-heavy columns that are rarely filtered.',
    commonMistakes:
      'No index on FKs, wrong composite order, over-indexing, and not reading EXPLAIN to confirm usage.',
    tradeoffs: 'Read speed vs. write overhead and storage.',
    realWorldExamples: 'A composite index on (tenant_id, created_at, id) powering tenant-scoped cursor pagination.',
    related: ['pagination', 'transactions', 'database-locks'],
    tags: ['index', 'postgres', 'performance'],
  },
  {
    slug: 'transactions',
    title: 'Transactions',
    category: 'database',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'critical',
    summary: 'Grouping operations so they all succeed or all fail, atomically.',
    mentalModel: 'A transaction is a "do all of this as one indivisible step, or none of it" wrapper with ACID guarantees.',
    howItWorks:
      'BEGIN ... COMMIT wraps statements; on error, ROLLBACK undoes them. The database enforces atomicity, consistency, isolation, and durability. Keep transactions short to avoid lock contention.',
    whenToUse: 'Multi-row invariants: money transfers, idempotency-key + effect, inventory decrements.',
    whenNotToUse: 'Single-statement writes (already atomic) or long-running external calls inside a transaction.',
    commonMistakes:
      'External API calls inside a transaction (holding locks), long transactions, and forgetting that the app-level effect and its bookkeeping must share one transaction.',
    tradeoffs: 'Correctness/atomicity vs. lock contention and reduced concurrency.',
    realWorldExamples: 'Drizzle db.transaction() wrapping a balance debit + credit + ledger insert.',
    related: ['isolation-levels', 'database-locks', 'idempotency', 'connection-pooling'],
    tags: ['transaction', 'acid', 'postgres'],
  },
  {
    slug: 'isolation-levels',
    title: 'Isolation levels',
    category: 'database',
    difficulty: 'advanced',
    status: 'needs-review',
    importance: 'high',
    summary: 'How much concurrent transactions can see of each other’s in-flight changes.',
    mentalModel: 'Isolation is a dial between "fast but anomalies possible" and "correct but more conflicts".',
    howItWorks:
      'Read Committed (Postgres default) prevents dirty reads but allows non-repeatable/phantom reads. Repeatable Read uses a snapshot. Serializable behaves as if transactions ran one at a time, aborting on conflicts (retry needed).',
    whenToUse: 'Raise isolation for read-modify-write invariants (balances, counters, booking).',
    whenNotToUse: 'Simple independent writes where the default is fine.',
    commonMistakes:
      'Assuming the default prevents lost updates, read-modify-write without locking/SELECT FOR UPDATE, and not retrying serialization failures.',
    tradeoffs: 'Higher isolation = fewer anomalies but more aborts/contention.',
    realWorldExamples: 'Serializable + retry for a seat-booking race; SELECT ... FOR UPDATE on a balance row.',
    related: ['transactions', 'database-locks'],
    prerequisites: ['transactions'],
    tags: ['isolation', 'concurrency', 'postgres'],
  },
  {
    slug: 'database-locks',
    title: 'Database locks',
    category: 'database',
    difficulty: 'advanced',
    status: 'reading',
    importance: 'medium',
    summary: 'Mechanisms that serialize access to rows to preserve consistency.',
    mentalModel: 'A lock is a "hands off, I’m using this" tag the DB places on rows or tables.',
    howItWorks:
      'Row locks (SELECT FOR UPDATE) block conflicting writers; advisory locks coordinate app-level critical sections. Deadlocks occur when two transactions wait on each other; the DB aborts one.',
    whenToUse: 'Read-modify-write on contended rows, leader election, single-runner cron.',
    whenNotToUse: 'Hot paths where locking creates a bottleneck (consider queues or optimistic concurrency).',
    commonMistakes: 'Inconsistent lock ordering (deadlocks), long-held locks, and locking more than needed.',
    tradeoffs: 'Pessimistic locks are simple and safe but reduce concurrency.',
    realWorldExamples: 'A Postgres advisory lock ensuring only one worker runs a migration step.',
    related: ['transactions', 'isolation-levels'],
    prerequisites: ['transactions'],
    tags: ['locks', 'concurrency'],
  },
  {
    slug: 'migrations',
    title: 'Migrations',
    category: 'database',
    difficulty: 'intermediate',
    status: 'understood',
    importance: 'high',
    summary: 'Versioned, repeatable changes to your database schema.',
    mentalModel: 'Migrations are git for your schema — ordered, reviewable, and applied the same way everywhere.',
    howItWorks:
      'A tool generates SQL diffs from your schema, records applied versions, and applies pending ones. Expand/contract patterns let you deploy schema changes without downtime.',
    whenToUse: 'Every schema change in any environment.',
    whenNotToUse: 'Never edit production schema by hand.',
    commonMistakes:
      'Destructive changes without a backfill, long-locking ALTERs on big tables, and editing already-applied migrations.',
    tradeoffs: 'Safety and reproducibility vs. discipline and multi-step rollouts for risky changes.',
    realWorldExamples: 'drizzle-kit generate/migrate; add-column then backfill then enforce-not-null.',
    related: ['transactions', 'backups'],
    tags: ['migrations', 'drizzle', 'schema'],
  },
  {
    slug: 'backups',
    title: 'Backups & recovery',
    category: 'database',
    difficulty: 'beginner',
    status: 'not-started',
    importance: 'high',
    summary: 'Being able to restore data after loss or corruption.',
    mentalModel: 'A backup you have never restored is a hope, not a backup.',
    howItWorks:
      'Automated snapshots plus point-in-time recovery (WAL) let you restore to a moment. Define RPO (how much data you can lose) and RTO (how fast you must recover), and test restores.',
    whenToUse: 'Any system holding data you cannot recreate.',
    whenNotToUse: 'Purely derived/ephemeral data you can rebuild.',
    commonMistakes: 'Never testing restores, no PITR, and backups in the same blast radius as production.',
    tradeoffs: 'Retention/coverage vs. storage cost.',
    realWorldExamples: 'Neon point-in-time restore to just before a bad migration.',
    related: ['migrations', 'reliability'],
    tags: ['backups', 'recovery'],
  },
  {
    slug: 'multi-tenancy',
    title: 'Multi-tenancy',
    category: 'database',
    difficulty: 'advanced',
    status: 'practicing',
    importance: 'critical',
    summary: 'Serving many isolated customers from shared infrastructure.',
    mentalModel:
      'Every row belongs to a tenant. The cardinal sin is letting one tenant ever see another’s data. Isolation must be enforced where queries run, not where UIs render.',
    howItWorks:
      'Models: shared schema with a tenant_id column (simplest, most common), schema-per-tenant, or database-per-tenant (strongest isolation, more ops). With shared schema, every query is scoped by tenant_id, ideally via a guarded query layer and/or Postgres row-level security.',
    whenToUse: 'B2B SaaS, anything serving multiple organizations.',
    whenNotToUse: 'Single-customer/internal tools, or when strict compliance demands physical isolation (then DB-per-tenant).',
    commonMistakes:
      'Forgetting tenant_id on one query (cross-tenant leak), trusting a client-sent tenant id, and no composite indexes on (tenant_id, ...).',
    tradeoffs:
      'Shared schema is cheap and easy to operate but isolation is your code’s responsibility; DB-per-tenant is isolated but operationally heavy.',
    realWorldExamples: 'A guarded repository that injects tenant_id into every query; Postgres RLS as a backstop.',
    related: ['authorization', 'security', 'postgresql-indexing', 'audit-logs'],
    prerequisites: ['authorization'],
    tags: ['multi-tenancy', 'isolation', 'saas'],
  },

  // --- Storage -------------------------------------------------------------
  {
    slug: 'file-storage',
    title: 'File storage',
    category: 'storage',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'medium',
    summary: 'Where and how to store user-uploaded files.',
    mentalModel: 'Files do not belong in your database or your function’s disk — they belong in object storage.',
    howItWorks:
      'Clients upload directly to object storage via presigned URLs; you store only metadata + the key in your DB. Serve via CDN.',
    whenToUse: 'Images, documents, audio/video, exports.',
    whenNotToUse: 'Tiny structured blobs better kept in the DB.',
    commonMistakes: 'Proxying large uploads through a function, storing files on ephemeral disk, public buckets by default.',
    tradeoffs: 'Direct-to-storage is scalable but needs presigning and validation.',
    realWorldExamples: 'PodCut uploading audio to R2 via a presigned URL, storing the key in Postgres.',
    related: ['object-storage', 'serverless-functions'],
    tags: ['files', 'uploads', 'r2'],
  },
  {
    slug: 'object-storage',
    title: 'Object storage',
    category: 'storage',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'medium',
    summary: 'Durable, scalable blob storage addressed by key (S3/R2).',
    mentalModel: 'A giant, durable key→bytes map with HTTP access and lifecycle rules.',
    howItWorks:
      'Buckets hold objects keyed by path. Access via signed URLs or IAM. Lifecycle rules expire/transition objects. Strong durability, eventual listing consistency historically.',
    whenToUse: 'Any large/binary asset, backups, static hosting.',
    whenNotToUse: 'Low-latency structured queries (use a DB).',
    commonMistakes: 'Public buckets, no lifecycle policy, and embedding credentials in clients.',
    tradeoffs: 'Cheap and durable vs. no rich querying and egress costs.',
    realWorldExamples: 'Cloudflare R2 (no egress fees) for user assets.',
    related: ['file-storage', 'cdn'],
    tags: ['s3', 'r2', 'blob'],
  },

  // --- Observability & reliability ----------------------------------------
  {
    slug: 'observability',
    title: 'Observability',
    category: 'observability',
    difficulty: 'intermediate',
    status: 'practicing',
    importance: 'high',
    summary: 'Being able to ask new questions about your running system without shipping new code.',
    mentalModel:
      'Logs, metrics, and traces are the three pillars. Logs are events, metrics are aggregates, traces are request journeys. Together they answer "what, how much, and where".',
    howItWorks:
      'Emit structured logs with correlation ids, expose metrics (rate, errors, duration), and propagate trace context across services. Dashboards and alerts turn that data into action.',
    whenToUse: 'From day one for anything you operate; deeper as traffic grows.',
    whenNotToUse: 'Throwaway prototypes.',
    commonMistakes: 'Unstructured logs, no correlation ids, alerting on causes instead of symptoms, and logging secrets.',
    tradeoffs: 'Insight and faster incident resolution vs. cost and instrumentation effort.',
    realWorldExamples: 'A small SaaS with structured request logs, a RED-metrics dashboard, and a few SLO alerts.',
    related: ['logging', 'metrics', 'tracing', 'sli-slo', 'incident-response'],
    tags: ['observability', 'monitoring'],
  },
  {
    slug: 'logging',
    title: 'Logging',
    category: 'observability',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'medium',
    summary: 'Structured, queryable records of what happened.',
    mentalModel: 'Logs are events with context — write them for the person debugging at 2am (often you).',
    howItWorks:
      'Emit JSON logs with level, timestamp, message, and fields (request id, user/tenant, duration). Centralize and index them.',
    whenToUse: 'Always, for meaningful events and errors.',
    whenNotToUse: 'Hot loops (sampling/aggregation instead) and secrets/PII.',
    commonMistakes: 'console.log strings, no correlation id, over-logging, and leaking secrets.',
    tradeoffs: 'Detail vs. cost and noise.',
    realWorldExamples: 'A logger helper that attaches request id and tenant to every line.',
    related: ['observability', 'metrics', 'tracing'],
    tags: ['logging', 'structured'],
  },
  {
    slug: 'metrics',
    title: 'Metrics',
    category: 'observability',
    difficulty: 'intermediate',
    status: 'reading',
    importance: 'medium',
    summary: 'Numeric aggregates over time that are cheap to store and alert on.',
    mentalModel: 'Metrics answer "how much / how fast / how often" — counters, gauges, histograms.',
    howItWorks:
      'Track RED (Rate, Errors, Duration) per endpoint and USE for resources. Use percentiles (p95/p99), not averages, for latency.',
    whenToUse: 'Dashboards, capacity planning, SLOs, alerting.',
    whenNotToUse: 'Per-request forensic detail (that is logs/traces).',
    commonMistakes: 'Averaging latency, high-cardinality labels exploding cost, and alerting on every metric.',
    tradeoffs: 'Cheap aggregates vs. loss of per-event detail.',
    realWorldExamples: 'p95 latency and error-rate panels per route.',
    related: ['observability', 'sli-slo'],
    tags: ['metrics', 'red'],
  },
  {
    slug: 'tracing',
    title: 'Distributed tracing',
    category: 'observability',
    difficulty: 'advanced',
    status: 'not-started',
    importance: 'low',
    summary: 'Following a single request across services and spans.',
    mentalModel: 'A trace is the request’s itinerary; spans are the legs of the journey with timings.',
    howItWorks:
      'A trace id is generated at the edge and propagated via headers. Each operation records a span (start, end, attributes). A tracing backend reconstructs the tree.',
    whenToUse: 'Multi-service systems where latency/errors cross boundaries.',
    whenNotToUse: 'A single monolith where logs+metrics suffice.',
    commonMistakes: 'Not propagating context, sampling everything (cost) or nothing (blind), and missing DB spans.',
    tradeoffs: 'Pinpoint cross-service insight vs. instrumentation and cost.',
    realWorldExamples: 'OpenTelemetry trace spanning API → queue → worker → DB.',
    related: ['observability', 'logging'],
    tags: ['tracing', 'otel'],
  },
  {
    slug: 'health-checks',
    title: 'Health checks',
    category: 'reliability',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'medium',
    summary: 'Endpoints that report whether an instance is alive and ready.',
    mentalModel: 'Liveness = "am I running?"; readiness = "can I serve traffic (deps OK)?".',
    howItWorks:
      'A /health endpoint checks critical dependencies (DB ping) and returns 200/503. Orchestrators use it to route traffic and restart bad instances.',
    whenToUse: 'Any deployed service, especially behind a load balancer.',
    whenNotToUse: 'Pure static sites.',
    commonMistakes: 'Health checks that always return 200, or that are so heavy they cause load.',
    tradeoffs: 'Deep checks catch more but can cascade failures; keep them light.',
    realWorldExamples: 'A readiness probe that pings Postgres with a 1s timeout.',
    related: ['observability', 'incident-response'],
    tags: ['health', 'probes'],
  },
  {
    slug: 'sli-slo',
    title: 'SLI / SLO',
    category: 'reliability',
    difficulty: 'advanced',
    status: 'reading',
    importance: 'high',
    summary: 'Measuring reliability with indicators and committing to targets.',
    mentalModel:
      'An SLI is a measurement (e.g. % of requests < 300ms). An SLO is the target (99.9%). The gap you may "spend" is the error budget.',
    howItWorks:
      'Pick user-centric SLIs (availability, latency), set realistic SLOs, measure continuously, and use the error budget to balance feature velocity vs. reliability work.',
    whenToUse: 'Once you have users who care about reliability.',
    whenNotToUse: 'Pre-PMF prototypes (premature).',
    commonMistakes: '100% targets, vanity SLIs, and SLOs nobody acts on.',
    tradeoffs: 'Clear reliability goals vs. measurement overhead.',
    realWorldExamples: '99.9% availability SLO; alert when burn rate threatens the monthly budget.',
    related: ['error-budget', 'metrics', 'observability', 'incident-response'],
    prerequisites: ['metrics'],
    tags: ['slo', 'reliability'],
  },
  {
    slug: 'error-budget',
    title: 'Error budget',
    category: 'reliability',
    difficulty: 'advanced',
    status: 'not-started',
    importance: 'medium',
    summary: 'The allowed amount of unreliability derived from an SLO.',
    mentalModel: 'If your SLO is 99.9%, you may be "down" 0.1% — that is a budget to spend on risk.',
    howItWorks:
      'Budget = 1 - SLO over a window. Burning it fast triggers a freeze on risky changes; plenty left means you can ship faster.',
    whenToUse: 'Teams balancing velocity and reliability with SLOs.',
    whenNotToUse: 'No SLOs yet.',
    commonMistakes: 'Treating the budget as theoretical and never acting on burn.',
    tradeoffs: 'Objective velocity/reliability tradeoff vs. requiring SLO discipline.',
    realWorldExamples: 'Pausing feature launches when 80% of the monthly budget is burned in a week.',
    related: ['sli-slo', 'incident-response'],
    prerequisites: ['sli-slo'],
    tags: ['error-budget', 'slo'],
  },
  {
    slug: 'incident-response',
    title: 'Incident response',
    category: 'reliability',
    difficulty: 'intermediate',
    status: 'not-started',
    importance: 'medium',
    summary: 'A repeatable process for detecting, mitigating, and learning from outages.',
    mentalModel: 'Mitigate first, diagnose second. Blameless postmortems turn pain into prevention.',
    howItWorks:
      'Detect (alerts) → declare + assign a commander → mitigate (rollback, failover) → communicate → resolve → blameless postmortem with action items.',
    whenToUse: 'Any system with users depending on uptime.',
    whenNotToUse: 'Solo prototypes.',
    commonMistakes: 'Debugging before mitigating, no clear owner, and skipping postmortems.',
    tradeoffs: 'Process overhead vs. faster, calmer recovery.',
    realWorldExamples: 'A runbook: how to roll back a deploy and flush a poisoned queue.',
    related: ['sli-slo', 'observability', 'health-checks'],
    tags: ['incident', 'oncall'],
  },
  {
    slug: 'circuit-breaker',
    title: 'Circuit breaker',
    category: 'reliability',
    difficulty: 'advanced',
    status: 'not-started',
    importance: 'medium',
    summary: 'Stopping calls to a failing dependency to let it recover.',
    mentalModel: 'Like an electrical breaker: trip open after repeated failures, then test cautiously before closing.',
    howItWorks:
      'Track failures; when a threshold trips, "open" the circuit and fail fast (or use a fallback). After a cooldown, allow a trial request ("half-open") before fully closing.',
    whenToUse: 'Calls to flaky external dependencies that can cascade failures.',
    whenNotToUse: 'Internal calls where retries+timeouts suffice.',
    commonMistakes: 'No timeout (the real killer), tripping too eagerly, and no fallback.',
    tradeoffs: 'Prevents cascading failure vs. added complexity and tuning.',
    realWorldExamples: 'Breaking calls to a degraded third-party API and serving cached/fallback data.',
    related: ['retry-strategy', 'backpressure', 'incident-response'],
    tags: ['circuit-breaker', 'resilience'],
  },
  {
    slug: 'backpressure',
    title: 'Backpressure',
    category: 'reliability',
    difficulty: 'advanced',
    status: 'not-started',
    importance: 'medium',
    summary: 'Signaling upstream to slow down when a system is overloaded.',
    mentalModel: 'When the sink is full, push back on the source instead of buffering until you crash.',
    howItWorks:
      'Bounded queues, 429/503 with Retry-After, concurrency limits, and load shedding tell producers to slow or stop. Pairs with rate limiting and circuit breakers.',
    whenToUse: 'Systems with variable load and downstream limits.',
    whenNotToUse: 'Low, predictable traffic.',
    commonMistakes: 'Unbounded queues (delayed collapse), no shedding, and silently dropping work.',
    tradeoffs: 'Stability under load vs. rejecting some requests.',
    realWorldExamples: 'A webhook receiver returning 429 when its queue is saturated.',
    related: ['rate-limiting', 'queues', 'circuit-breaker'],
    tags: ['backpressure', 'load'],
  },

  // --- Architecture patterns ----------------------------------------------
  {
    slug: 'monolith',
    title: 'Monolith',
    category: 'architecture-pattern',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'medium',
    summary: 'A single deployable application containing all features.',
    mentalModel: 'One codebase, one deploy, one database — the simplest thing that works.',
    howItWorks: 'All modules run in one process and share a database; calls are in-process function calls.',
    whenToUse: 'Almost every new product and small team.',
    whenNotToUse: 'When independent scaling/teams genuinely require separate services.',
    commonMistakes: 'Premature microservices; or a "big ball of mud" monolith with no internal boundaries.',
    tradeoffs: 'Simplicity and speed vs. coupling at large scale.',
    realWorldExamples: 'A Next.js app with route handlers and Neon — most of the user’s SaaS.',
    related: ['modular-monolith', 'microservices'],
    tags: ['monolith', 'architecture'],
  },
  {
    slug: 'modular-monolith',
    title: 'Modular monolith',
    category: 'architecture-pattern',
    difficulty: 'intermediate',
    status: 'reading',
    importance: 'high',
    summary: 'A monolith with strong internal module boundaries.',
    mentalModel: 'Microservice-like boundaries (clear interfaces, owned data) without the network in between.',
    howItWorks:
      'Organize by domain modules with explicit public interfaces and private internals; modules talk via those interfaces, not each other’s tables.',
    whenToUse: 'Growing products that want future optionality without distributed-systems pain now.',
    whenNotToUse: 'Tiny apps (overhead) or when services are truly required.',
    commonMistakes: 'Boundaries on paper only; shared tables across modules.',
    tradeoffs: 'Most microservice benefits with far less operational cost vs. discipline to keep boundaries.',
    realWorldExamples: 'A SaaS split into billing/auth/core modules in one deploy, each owning its tables.',
    related: ['monolith', 'microservices', 'clean-architecture'],
    prerequisites: ['monolith'],
    tags: ['modular-monolith', 'boundaries'],
  },
  {
    slug: 'microservices',
    title: 'Microservices',
    category: 'architecture-pattern',
    difficulty: 'advanced',
    status: 'not-started',
    importance: 'medium',
    summary: 'Independently deployable services owning their own data.',
    mentalModel: 'Trade in-process simplicity for independent deploy/scale — and inherit a distributed system.',
    howItWorks:
      'Each service has its own database and API; they communicate over the network (sync or events). Requires service discovery, observability, and resilience patterns.',
    whenToUse: 'Large orgs needing independent team velocity and component-level scaling.',
    whenNotToUse: 'Small teams/products — the operational tax rarely pays off early.',
    commonMistakes: 'Distributed monolith (chatty, shared DB), no observability, and ignoring partial failure.',
    tradeoffs: 'Independent scaling/teams vs. network failure, data consistency, and ops complexity.',
    realWorldExamples: 'A platform splitting payments and notifications into separate services.',
    related: ['modular-monolith', 'event-driven-architecture', 'api-gateway', 'saga-pattern'],
    tags: ['microservices', 'distributed'],
  },
  {
    slug: 'event-driven-architecture',
    title: 'Event-driven architecture',
    category: 'architecture-pattern',
    difficulty: 'advanced',
    status: 'not-started',
    importance: 'medium',
    summary: 'Components communicate by emitting and reacting to events.',
    mentalModel: 'Producers announce facts ("OrderPlaced"); consumers react. The producer does not know who listens.',
    howItWorks:
      'Events flow through a broker/log. Consumers subscribe and process independently, enabling decoupling and fan-out. Demands idempotency and careful ordering.',
    whenToUse: 'Decoupling, fan-out to many reactions, audit trails, async workflows.',
    whenNotToUse: 'Simple request/response needs or when strong consistency is required.',
    commonMistakes: 'Treating events as commands, no schema versioning, and ignoring ordering/dedup.',
    tradeoffs: 'Loose coupling and extensibility vs. eventual consistency and harder debugging.',
    realWorldExamples: 'Emitting "UsageRecorded" events that several aggregators consume (BurnCap).',
    related: ['queues', 'outbox-pattern', 'cqrs', 'microservices'],
    tags: ['events', 'eda'],
  },
  {
    slug: 'cqrs',
    title: 'CQRS',
    category: 'architecture-pattern',
    difficulty: 'advanced',
    status: 'not-started',
    importance: 'low',
    summary: 'Separating the write model from the read model.',
    mentalModel: 'Optimize writes and reads independently — they have different shapes and load.',
    howItWorks:
      'Commands mutate the write model; a separate read model (often denormalized, possibly updated via events) serves queries. They can use different stores.',
    whenToUse: 'Read/write loads diverge sharply, or complex read views are expensive to compute live.',
    whenNotToUse: 'Most CRUD apps — it adds significant complexity.',
    commonMistakes: 'Applying CQRS everywhere; ignoring the sync lag between models.',
    tradeoffs: 'Independent optimization vs. complexity and eventual consistency between models.',
    realWorldExamples: 'A precomputed analytics read model updated from write-side events.',
    related: ['event-driven-architecture', 'outbox-pattern'],
    tags: ['cqrs', 'read-model'],
  },
  {
    slug: 'saga-pattern',
    title: 'Saga pattern',
    category: 'architecture-pattern',
    difficulty: 'advanced',
    status: 'not-started',
    importance: 'low',
    summary: 'Coordinating a multi-step workflow across services without a distributed transaction.',
    mentalModel: 'A chain of local transactions, each with a compensating action to undo if a later step fails.',
    howItWorks:
      'Orchestration (a coordinator drives steps) or choreography (services react to events). On failure, run compensations in reverse to restore consistency.',
    whenToUse: 'Cross-service workflows (order → payment → shipping) needing eventual consistency.',
    whenNotToUse: 'Single-database workflows (use a transaction).',
    commonMistakes: 'No compensations, assuming atomicity, and unbounded retries.',
    tradeoffs: 'Cross-service consistency vs. significant complexity.',
    realWorldExamples: 'Booking flow that compensates a charge if reservation fails.',
    related: ['event-driven-architecture', 'microservices', 'idempotency'],
    tags: ['saga', 'workflow'],
  },
  {
    slug: 'outbox-pattern',
    title: 'Outbox pattern',
    category: 'architecture-pattern',
    difficulty: 'advanced',
    status: 'not-started',
    importance: 'medium',
    summary: 'Reliably publishing events as part of a database transaction.',
    mentalModel: 'Write the event to an outbox table in the same transaction as the state change; a relay publishes it later.',
    howItWorks:
      'Within one transaction, update state and insert an outbox row. A separate process polls/streams the outbox and publishes to the broker, marking rows done. Solves the dual-write problem.',
    whenToUse: 'When a state change must reliably produce an event (no lost or phantom events).',
    whenNotToUse: 'When you have no external event consumers.',
    commonMistakes: 'Dual writes (DB then broker) without an outbox — crashes cause inconsistency; no dedup downstream.',
    tradeoffs: 'Reliable eventing vs. a relay process and at-least-once delivery.',
    realWorldExamples: 'Insert an outbox row when a payment is recorded; a relay publishes "PaymentRecorded".',
    related: ['event-driven-architecture', 'transactions', 'queues', 'idempotency'],
    prerequisites: ['transactions'],
    tags: ['outbox', 'events', 'consistency'],
  },
  {
    slug: 'api-gateway',
    title: 'API gateway',
    category: 'architecture-pattern',
    difficulty: 'intermediate',
    status: 'not-started',
    importance: 'low',
    summary: 'A single entry point that routes, authenticates, and rate-limits requests to backends.',
    mentalModel: 'A front door that handles cross-cutting concerns so each service does not have to.',
    howItWorks:
      'The gateway terminates TLS, authenticates, rate-limits, routes to services, and can aggregate responses.',
    whenToUse: 'Many backend services needing shared auth/routing/limits.',
    whenNotToUse: 'A single app (the framework already does this).',
    commonMistakes: 'Putting business logic in the gateway; making it a single point of failure.',
    tradeoffs: 'Centralized cross-cutting concerns vs. another hop and component to operate.',
    realWorldExamples: 'A gateway enforcing auth + rate limits in front of microservices.',
    related: ['microservices', 'rate-limiting', 'backend-for-frontend'],
    tags: ['gateway', 'routing'],
  },
  {
    slug: 'backend-for-frontend',
    title: 'Backend for frontend',
    category: 'architecture-pattern',
    difficulty: 'intermediate',
    status: 'not-started',
    importance: 'low',
    summary: 'A tailored backend layer serving a specific frontend’s needs.',
    mentalModel: 'One backend per client type, shaping data exactly how that UI wants it.',
    howItWorks:
      'The BFF aggregates/transforms downstream services into client-optimized responses, reducing round-trips and over-fetching for that client.',
    whenToUse: 'Different clients (web/mobile) with very different data needs over shared services.',
    whenNotToUse: 'A single client where the main API already fits.',
    commonMistakes: 'Duplicating business logic across BFFs; turning the BFF into a monolith.',
    tradeoffs: 'Client-optimized APIs vs. more services to maintain.',
    realWorldExamples: 'Next.js route handlers acting as a BFF aggregating several APIs for the web app.',
    related: ['api-gateway', 'rest-api-design'],
    tags: ['bff', 'aggregation'],
  },
  {
    slug: 'clean-architecture',
    title: 'Clean architecture',
    category: 'architecture-pattern',
    difficulty: 'intermediate',
    status: 'reading',
    importance: 'medium',
    summary: 'Organizing code so business rules do not depend on frameworks or I/O.',
    mentalModel: 'Dependencies point inward: domain logic at the center, frameworks/DB at the edges behind interfaces.',
    howItWorks:
      'Use cases orchestrate domain entities and depend on abstract ports; adapters (DB, HTTP) implement those ports. Swappable infrastructure, testable core.',
    whenToUse: 'Complex domains with long-lived business rules.',
    whenNotToUse: 'Simple CRUD where the indirection costs more than it saves.',
    commonMistakes: 'Over-abstracting trivial apps; leaking framework types into the core.',
    tradeoffs: 'Testability and flexibility vs. more layers and ceremony.',
    realWorldExamples: 'A service layer with repository interfaces that Drizzle implements.',
    related: ['layered-architecture', 'modular-monolith'],
    tags: ['clean-architecture', 'design'],
  },
  {
    slug: 'layered-architecture',
    title: 'Layered architecture',
    category: 'architecture-pattern',
    difficulty: 'beginner',
    status: 'understood',
    importance: 'medium',
    summary: 'Separating code into presentation, application, domain, and data layers.',
    mentalModel: 'Each layer talks only to the one below it; concerns are separated by responsibility.',
    howItWorks:
      'Controllers/handlers → services (use cases) → repositories (data). Validation at the edge, business logic in services, I/O in repositories.',
    whenToUse: 'Most apps benefit from at least handler/service/data separation.',
    whenNotToUse: 'Trivial scripts.',
    commonMistakes: 'Fat controllers with business logic; queries scattered across handlers.',
    tradeoffs: 'Clarity and testability vs. some boilerplate.',
    realWorldExamples: 'This very app: route handlers/actions → db/queries → Drizzle.',
    related: ['clean-architecture', 'modular-monolith'],
    tags: ['layers', 'structure'],
  },
  {
    slug: 'system-design-tradeoffs',
    title: 'System design trade-offs',
    category: 'system-design',
    difficulty: 'advanced',
    status: 'reading',
    importance: 'critical',
    summary: 'There is no best architecture — only the right trade-offs for your constraints.',
    mentalModel:
      'Every choice trades something: consistency vs. availability, latency vs. cost, simplicity vs. flexibility. Name the constraint, then choose.',
    howItWorks:
      'Gather requirements and traffic, estimate load, pick a data model and access patterns, then choose scaling/consistency/reliability strategies that fit — and write down what you traded away.',
    whenToUse: 'Every design review and architecture decision.',
    whenNotToUse: '',
    commonMistakes: 'Resume-driven design, optimizing for imaginary scale, and not stating assumptions.',
    tradeoffs: 'The meta-concept: making trade-offs explicit beats pretending there is a free lunch.',
    realWorldExamples: 'Choosing a modular monolith on serverless for a solo SaaS instead of microservices.',
    related: ['system-design-tradeoffs', 'modular-monolith', 'caching', 'queues', 'multi-tenancy'],
    tags: ['system-design', 'tradeoffs'],
  },
];
