import type { GlossarySeed } from './types';

export const glossarySeeds: GlossarySeed[] = [
  {
    term: 'Idempotency',
    category: 'api-design',
    definition:
      'A property where performing an operation multiple times has the same effect as performing it once.',
    example: 'A payment endpoint keyed by an Idempotency-Key returns the original result on retry instead of charging twice.',
    commonConfusion: 'Not the same as "safe" (read-only). A DELETE is idempotent but not safe.',
    relatedConceptSlugs: ['idempotency', 'webhooks', 'retry-strategy'],
  },
  {
    term: 'Transaction',
    category: 'database',
    definition: 'A group of operations that succeed or fail as a single atomic unit (ACID).',
    example: 'Debit and credit two accounts plus write a ledger row — all commit together or none do.',
    commonConfusion: 'A transaction guarantees atomicity, but the default isolation level still allows some anomalies.',
    relatedConceptSlugs: ['transactions', 'isolation-levels'],
  },
  {
    term: 'Isolation level',
    category: 'database',
    definition: 'How visible concurrent transactions’ in-flight changes are to each other.',
    example: 'Postgres defaults to Read Committed; SERIALIZABLE behaves as if transactions ran one at a time.',
    commonConfusion: 'Higher isolation does not just mean "safer" for free — it means more conflicts/aborts to retry.',
    relatedConceptSlugs: ['isolation-levels', 'transactions', 'database-locks'],
  },
  {
    term: 'Dead letter queue (DLQ)',
    category: 'queue',
    definition: 'A separate queue holding messages that repeatedly failed processing.',
    example: 'After 5 failed attempts, a job moves to the DLQ and triggers an alert for inspection.',
    commonConfusion: 'A DLQ is not a retry mechanism — it is where messages go after retries are exhausted.',
    relatedConceptSlugs: ['dead-letter-queue', 'queues', 'retry-strategy'],
  },
  {
    term: 'Backpressure',
    category: 'reliability',
    definition: 'Signaling upstream producers to slow down when a system is overloaded.',
    example: 'A saturated webhook receiver returns 429 with Retry-After instead of buffering until it crashes.',
    commonConfusion: 'Not the same as rate limiting — backpressure is a reaction to load; rate limiting is a fixed policy.',
    relatedConceptSlugs: ['backpressure', 'rate-limiting', 'queues'],
  },
  {
    term: 'Retry',
    category: 'reliability',
    definition: 'Re-attempting a failed operation, ideally only for transient errors and with backoff.',
    example: 'Retry a 503 with exponential backoff + jitter, up to 5 attempts, then dead-letter.',
    commonConfusion: 'Retrying non-idempotent operations can duplicate effects — retries need idempotency.',
    relatedConceptSlugs: ['retry-strategy', 'idempotency'],
  },
  {
    term: 'Timeout',
    category: 'reliability',
    definition: 'A maximum time to wait for an operation before failing it.',
    example: 'A 1s database timeout in a readiness probe so a hung DB does not hang the probe.',
    commonConfusion: 'Missing timeouts are the silent killer — they let slow dependencies cascade into outages.',
    relatedConceptSlugs: ['circuit-breaker', 'retry-strategy', 'health-checks'],
  },
  {
    term: 'Circuit breaker',
    category: 'reliability',
    definition: 'A mechanism that stops calls to a failing dependency to let it recover.',
    example: 'After repeated failures the breaker "opens" and fails fast, testing recovery before closing.',
    commonConfusion: 'A breaker complements timeouts and retries — it does not replace them.',
    relatedConceptSlugs: ['circuit-breaker', 'retry-strategy', 'backpressure'],
  },
  {
    term: 'Rate limit',
    category: 'rate-limiting',
    definition: 'A cap on how many requests a client may make within a time window.',
    example: 'X-RateLimit-Remaining headers and 429 responses on a public API.',
    commonConfusion: 'In-memory limiters are wrong on serverless — counters must be shared across instances.',
    relatedConceptSlugs: ['rate-limiting', 'backpressure'],
  },
  {
    term: 'Cache invalidation',
    category: 'caching',
    definition: 'Removing or refreshing cached data when the source of truth changes.',
    example: 'Purging or tag-invalidating a cached entity on write; or relying on a short TTL.',
    commonConfusion: 'TTL alone does not guarantee freshness — it bounds staleness, it does not eliminate it.',
    relatedConceptSlugs: ['cache-invalidation', 'caching'],
  },
  {
    term: 'SLO',
    category: 'reliability',
    definition: 'A Service Level Objective — a target for a reliability indicator over a window.',
    example: '99.9% of requests succeed within 300ms over 30 days.',
    commonConfusion: 'An SLO (target) is not an SLA (contract with penalties) nor an SLI (the measurement).',
    relatedConceptSlugs: ['sli-slo', 'error-budget', 'metrics'],
  },
  {
    term: 'Error budget',
    category: 'reliability',
    definition: 'The allowed amount of unreliability, computed as 1 − SLO.',
    example: 'A 99.9% SLO permits ~43 minutes of downtime per month — that is the budget.',
    commonConfusion: 'It is a decision tool, not just a number — burning it should change behavior.',
    relatedConceptSlugs: ['error-budget', 'sli-slo'],
  },
  {
    term: 'Tenant isolation',
    category: 'security',
    definition: 'Guaranteeing one tenant can never access another tenant’s data.',
    example: 'Every query scoped by tenant_id via a guarded layer, backed by Postgres RLS.',
    commonConfusion: 'Filtering in the UI is not isolation — isolation must be enforced where queries run.',
    relatedConceptSlugs: ['multi-tenancy', 'authorization', 'security'],
  },
  {
    term: 'Cursor pagination',
    category: 'api-design',
    definition: 'Paginating by an opaque marker of the last seen row instead of a numeric offset.',
    example: 'WHERE (created_at, id) < (cursor) ORDER BY created_at DESC, id DESC LIMIT n.',
    commonConfusion: 'Cursors cannot jump to an arbitrary page number — they are sequential.',
    relatedConceptSlugs: ['pagination', 'postgresql-indexing'],
  },
  {
    term: 'Connection pooling',
    category: 'database',
    definition: 'Reusing a bounded set of database connections instead of opening one per request.',
    example: 'Serverless functions connect through Neon’s pooled endpoint (PgBouncer).',
    commonConfusion: 'Transaction-mode pooling does not support every session-level feature (e.g. some prepared-statement use).',
    relatedConceptSlugs: ['connection-pooling', 'serverless-functions'],
  },
  {
    term: 'Cold start',
    category: 'serverless',
    definition: 'The latency penalty when a new function instance must boot before serving a request.',
    example: 'The first request after idle is slow while the runtime and module initialize.',
    commonConfusion: 'Cold starts affect tail latency, not average — they are about the unlucky first request.',
    relatedConceptSlugs: ['cold-starts', 'serverless-functions'],
  },
  {
    term: 'Webhook signature',
    category: 'security',
    definition: 'An HMAC over the webhook payload that proves it came from the real provider.',
    example: 'Verify the Stripe-Signature header against your endpoint secret before parsing.',
    commonConfusion: 'Verify against the RAW body — parsing/re-serializing first can break the signature.',
    relatedConceptSlugs: ['webhooks', 'security'],
  },
  {
    term: 'Outbox pattern',
    category: 'architecture-pattern',
    definition: 'Writing events to an outbox table in the same transaction as the state change, then relaying them.',
    example: 'Insert an "outbox" row when recording a payment; a relay publishes it to the broker.',
    commonConfusion: 'It solves the dual-write problem; it does not give exactly-once delivery (consumers still dedupe).',
    relatedConceptSlugs: ['outbox-pattern', 'event-driven-architecture', 'transactions'],
  },
  {
    term: 'Saga',
    category: 'architecture-pattern',
    definition: 'A sequence of local transactions across services with compensating actions on failure.',
    example: 'Order → payment → shipping, with a refund compensation if shipping fails.',
    commonConfusion: 'A saga is not a distributed transaction — it provides eventual consistency, not atomicity.',
    relatedConceptSlugs: ['saga-pattern', 'event-driven-architecture'],
  },
  {
    term: 'CQRS',
    category: 'architecture-pattern',
    definition: 'Command Query Responsibility Segregation — separate write and read models.',
    example: 'A denormalized read model updated from write-side events powers fast dashboards.',
    commonConfusion: 'CQRS does not require event sourcing, and it is overkill for most CRUD apps.',
    relatedConceptSlugs: ['cqrs', 'event-driven-architecture'],
  },
  {
    term: 'Read replica',
    category: 'scalability',
    definition: 'A read-only copy of the database that serves read queries to offload the primary.',
    example: 'Route analytics/reporting reads to a replica; writes still go to the primary.',
    commonConfusion: 'Replicas lag — reads can be slightly stale, so do not read-your-own-writes from them.',
    relatedConceptSlugs: ['scalability', 'caching'],
  },
];
