import type { LearningLogSeed } from './types';

// Recent days (0–4) are consecutive to seed a 5-day streak; older entries fill charts.
export const learningLogSeeds: LearningLogSeed[] = [
  {
    daysAgo: 0,
    title: 'Spaced review + isolation levels',
    summary:
      'Ran my due review cards and finally reproduced a lost update with two concurrent transactions.',
    conceptsStudied: ['isolation-levels', 'transactions'],
    timeSpentMinutes: 55,
    confidenceChange: 2,
    blockers: 'Still fuzzy on when SERIALIZABLE is worth it over SELECT FOR UPDATE.',
    notes: 'Doing the arithmetic in SQL is the cleanest fix for lost updates.',
    nextStep: 'Write the isolation-levels lesson and a review card for serialization retries.',
  },
  {
    daysAgo: 1,
    title: 'Rate limiter lab',
    summary: 'Finished the three rate-limiting algorithms; token bucket clicked.',
    conceptsStudied: ['rate-limiting'],
    labsCompleted: ['implement-a-rate-limiter'],
    timeSpentMinutes: 95,
    confidenceChange: 3,
    notes: 'Atomicity across instances is the whole game — moving the math to Redis Lua next.',
    nextStep: 'Re-implement the limiter as a Redis Lua script.',
  },
  {
    daysAgo: 2,
    title: 'Webhook idempotency design',
    summary: 'Sketched the idempotent webhook handler; deciding inline-tx vs outbox.',
    conceptsStudied: ['webhooks', 'idempotency'],
    timeSpentMinutes: 40,
    confidenceChange: 1,
    blockers: 'Outbox vs in-transaction enqueue trade-off.',
    nextStep: 'Read the outbox pattern and decide for MergeAttest.',
  },
  {
    daysAgo: 3,
    title: 'Cursor pagination',
    summary: 'Completed the cursor pagination lab; tie-breaking on id is the trick.',
    conceptsStudied: ['pagination', 'postgresql-indexing'],
    labsCompleted: ['design-cursor-pagination'],
    timeSpentMinutes: 55,
    confidenceChange: 2,
    nextStep: 'Apply (tenant_id, created_at, id) indexing thinking to BurnCap.',
  },
  {
    daysAgo: 4,
    title: 'Payment race condition debug',
    summary: 'Fixed the lost-update bug in the wallet debit flow.',
    conceptsStudied: ['transactions'],
    labsCompleted: ['transaction-safe-payment-flow'],
    timeSpentMinutes: 70,
    confidenceChange: 3,
    notes: 'A transaction alone is NOT enough without locking or atomic SQL.',
    nextStep: 'Make the debit idempotent for retries.',
  },
  {
    daysAgo: 7,
    title: 'Caching fundamentals',
    summary: 'Read through caching + invalidation; the invalidation problem is the real one.',
    conceptsStudied: ['caching', 'cache-invalidation'],
    timeSpentMinutes: 50,
    confidenceChange: 1,
    nextStep: 'Plan SmartTrips plan_cache invalidation.',
  },
  {
    daysAgo: 9,
    title: 'Queues + DLQ',
    summary: 'Studied queues, retries, and dead-letter queues together.',
    conceptsStudied: ['queues', 'dead-letter-queue', 'retry-strategy'],
    timeSpentMinutes: 65,
    confidenceChange: 2,
    nextStep: 'Design the DueKind send queue.',
  },
  {
    daysAgo: 12,
    title: 'Multi-tenancy modeling',
    summary: 'Worked through shared-schema isolation and RLS as a backstop.',
    conceptsStudied: ['multi-tenancy', 'authorization'],
    timeSpentMinutes: 60,
    confidenceChange: 2,
    blockers: 'Getting the guarded query layer ergonomics right.',
    nextStep: 'Prototype a tenant-scoped query helper for the Eastbase starter.',
  },
  {
    daysAgo: 15,
    title: 'API conventions cleanup',
    summary: 'Standardized an error envelope and validation approach.',
    conceptsStudied: ['api-error-handling', 'api-validation'],
    timeSpentMinutes: 45,
    confidenceChange: 1,
    nextStep: 'Roll the error helper into Eastbase products.',
  },
  {
    daysAgo: 18,
    title: 'Serverless constraints',
    summary: 'Mapped out exactly when to graduate off serverless.',
    conceptsStudied: ['serverless-functions', 'cold-starts', 'connection-pooling'],
    timeSpentMinutes: 50,
    confidenceChange: 2,
    nextStep: 'Define DueKind’s migration threshold.',
  },
  {
    daysAgo: 22,
    title: 'Backend fundamentals refresh',
    summary: 'Re-grounded on the request lifecycle and REST design.',
    conceptsStudied: ['http-request-lifecycle', 'rest-api-design'],
    timeSpentMinutes: 40,
    confidenceChange: 1,
    nextStep: 'Move on to the practical SaaS module.',
  },
  {
    daysAgo: 25,
    title: 'Kickoff',
    summary: 'Set up the learning plan and modules; committed to a daily review habit.',
    timeSpentMinutes: 30,
    confidenceChange: 0,
    notes: 'Goal: rebuild backend architecture knowledge before deeper system design.',
    nextStep: 'Start Backend Fundamentals.',
  },
];
