import type { ModuleSeed } from './types';

export const moduleSeeds: ModuleSeed[] = [
  {
    slug: 'backend-fundamentals',
    title: 'Backend Fundamentals',
    moduleType: 'fundamentals',
    order: 1,
    estimatedHours: 12,
    status: 'completed',
    description:
      'The non-negotiable basics: how requests flow, how to design and validate APIs, how auth works, and how to model and persist data safely.',
    outcome:
      'Confidently design a REST endpoint with validation, error handling, auth, and a transaction-safe write.',
    notes:
      'This is the floor for everything else. Revisit error handling — my conventions still drift between projects.',
    conceptSlugs: [
      'http-request-lifecycle',
      'rest-api-design',
      'api-validation',
      'api-error-handling',
      'authentication',
      'authorization',
      'pagination',
      'transactions',
      'file-storage',
    ],
  },
  {
    slug: 'practical-saas-backend',
    title: 'Practical SaaS Backend',
    moduleType: 'practical-backend',
    order: 2,
    estimatedHours: 16,
    status: 'in-progress',
    description:
      'The backend features almost every SaaS needs: multi-tenancy, webhooks, background jobs, rate limiting, and audit logs.',
    outcome:
      'Ship a multi-tenant SaaS feature end-to-end with safe webhook handling and async jobs.',
    notes: 'Directly applicable to DueKind and BurnCap. Prioritize webhooks + idempotency.',
    conceptSlugs: [
      'multi-tenancy',
      'webhooks',
      'idempotency',
      'background-jobs',
      'rate-limiting',
      'audit-logs',
      'cron-jobs',
      'queues',
    ],
  },
  {
    slug: 'database-deep-dive',
    title: 'Database Deep Dive',
    moduleType: 'database-deep-dive',
    order: 3,
    estimatedHours: 14,
    status: 'in-progress',
    description:
      'Go past CRUD: indexing, transactions, isolation, locks, migrations, backups, and multi-tenant schemas in PostgreSQL.',
    outcome:
      'Reason about query plans, choose isolation levels, and design safe migrations on a live table.',
    notes: 'Isolation levels are the weak spot — keep practicing the lost-update scenarios.',
    conceptSlugs: [
      'postgresql-indexing',
      'transactions',
      'isolation-levels',
      'database-locks',
      'migrations',
      'backups',
      'multi-tenancy',
      'connection-pooling',
    ],
  },
  {
    slug: 'reliability-observability',
    title: 'Reliability & Observability',
    moduleType: 'reliability',
    order: 4,
    estimatedHours: 12,
    status: 'not-started',
    description:
      'Make systems you can see into and trust: health checks, logging, metrics, tracing, SLOs, error budgets, and incident response.',
    outcome: 'Define SLOs for a small SaaS and instrument it well enough to debug an incident.',
    conceptSlugs: [
      'health-checks',
      'logging',
      'metrics',
      'tracing',
      'sli-slo',
      'error-budget',
      'incident-response',
      'retry-strategy',
      'circuit-breaker',
    ],
  },
  {
    slug: 'architecture-patterns',
    title: 'Architecture Patterns',
    moduleType: 'architecture-patterns',
    order: 5,
    estimatedHours: 14,
    status: 'not-started',
    description:
      'From layered architecture to event-driven systems — and when each pattern earns its complexity.',
    outcome: 'Pick the right architecture for a given constraint and justify the trade-off.',
    conceptSlugs: [
      'layered-architecture',
      'clean-architecture',
      'modular-monolith',
      'microservices',
      'event-driven-architecture',
      'cqrs',
      'outbox-pattern',
      'saga-pattern',
      'api-gateway',
      'backend-for-frontend',
    ],
  },
  {
    slug: 'serverless-to-traditional-backend',
    title: 'Serverless → Traditional Backend',
    moduleType: 'serverless-to-traditional-backend',
    order: 6,
    estimatedHours: 10,
    status: 'in-progress',
    description:
      'Understand serverless constraints and learn exactly when to graduate to a long-running Node/Python backend.',
    outcome:
      'Decide, with evidence, when a project should move off serverless Next.js API routes.',
    notes: 'The migration decision keeps coming up for DueKind’s reminder pipeline.',
    conceptSlugs: [
      'serverless-functions',
      'cold-starts',
      'edge-functions',
      'connection-pooling',
      'queues',
      'cron-jobs',
      'background-jobs',
    ],
  },
  {
    slug: 'system-design-foundation',
    title: 'System Design Foundation',
    moduleType: 'system-design',
    order: 7,
    estimatedHours: 18,
    status: 'not-started',
    description:
      'A repeatable method for system design: requirements, estimation, data modeling, scaling reads/writes, caching, queues, consistency, and cost.',
    outcome: 'Run a full system-design interview-style pass and defend the trade-offs.',
    conceptSlugs: [
      'system-design-tradeoffs',
      'caching',
      'queues',
      'multi-tenancy',
      'postgresql-indexing',
      'rate-limiting',
      'observability',
    ],
  },
];
