import type { ProjectSeed } from './types';

export const projectSeeds: ProjectSeed[] = [
  {
    slug: 'smarttrips',
    projectName: 'SmartTrips',
    projectType: 'smarttrips',
    status: 'active',
    description: 'AI-assisted trip planner that aggregates slow external travel APIs into itineraries.',
    currentArchitecture:
      'Next.js App Router on Vercel, Neon Postgres, Drizzle, R2 for assets. Plan generation currently happens inline in a route handler.',
    backendRisks:
      'Generation blocks the request and is fragile when an upstream API is slow/down; no caching of identical generations; external API cost is uncontrolled.',
    conceptsUsedSlugs: ['rest-api-design', 'api-validation', 'caching', 'serverless-functions'],
    conceptsToLearnSlugs: ['queues', 'cache-invalidation', 'circuit-breaker', 'retry-strategy'],
    architectureNotes:
      'Move generation behind a queue with progress; cache finished plans by input hash; circuit-break degraded providers and serve partial plans.',
    improvementIdeas:
      'Add plan_cache keyed by trip_hash; per-provider timeouts + breakers; cap regenerations to control cost.',
    nextBackendAction: 'Extract trip generation into a queued worker with a trip_hash cache.',
    relatedDecisionGuideSlugs: ['do-i-need-a-queue', 'do-i-need-redis'],
    relatedCaseStudySlug: 'smarttrips-backend',
  },
  {
    slug: 'duekind',
    projectName: 'DueKind',
    projectType: 'duekind',
    status: 'active',
    description: 'Payment reminder tool that emails freelancers’ clients about due invoices.',
    currentArchitecture:
      'Next.js + Neon + Vercel Cron. Reminders are currently sent inline when the cron runs.',
    backendRisks:
      'Inline sending risks duplicates and provider-outage failures; business-hour spikes can overwhelm the email provider’s rate limit.',
    conceptsUsedSlugs: ['cron-jobs', 'rest-api-design', 'transactions'],
    conceptsToLearnSlugs: ['queues', 'idempotency', 'background-jobs', 'dead-letter-queue'],
    architectureNotes:
      'Cron should enqueue, not send. Worker sends with retries + DLQ; idempotency key = reminder id + scheduled date.',
    improvementIdeas:
      'Add a queue + worker; idempotent sends; cancel-on-paid; alert on DLQ depth.',
    nextBackendAction: 'Introduce a send queue and make reminder sends idempotent.',
    relatedDecisionGuideSlugs: ['do-i-need-a-queue', 'nextjs-api-vs-dedicated-backend', 'how-to-handle-retries'],
    relatedCaseStudySlug: 'duekind-reminder-system',
  },
  {
    slug: 'burncap',
    projectName: 'BurnCap',
    projectType: 'burncap',
    status: 'active',
    description: 'AI cost monitoring: ingest usage events and alert on budget caps.',
    currentArchitecture:
      'Next.js + Neon. Usage events are written directly; dashboards query raw events.',
    backendRisks:
      'Per-event synchronous writes and live aggregation over raw events will not scale; alert logic could fire repeatedly.',
    conceptsUsedSlugs: ['rest-api-design', 'postgresql-indexing', 'multi-tenancy'],
    conceptsToLearnSlugs: ['queues', 'event-driven-architecture', 'cqrs', 'backpressure'],
    architectureNotes:
      'Buffer ingestion with a queue; append-only raw events + rolled-up aggregates; idempotent budget alerts; index (tenant_id, recorded_at).',
    improvementIdeas:
      'Pre-aggregate per (tenant, day, model); retention/archival for raw events; backpressure on ingestion.',
    nextBackendAction: 'Split ingestion (queue + worker) from read-time aggregation (rollups).',
    relatedDecisionGuideSlugs: ['do-i-need-a-queue', 'do-i-need-event-driven-architecture'],
    relatedCaseStudySlug: 'burncap-cost-monitoring',
  },
  {
    slug: 'mergeattest',
    projectName: 'MergeAttest',
    projectType: 'mergeattest',
    status: 'active',
    description: 'GitHub PR attestation service driven by webhooks.',
    currentArchitecture: 'Next.js webhook endpoint + Neon; checks run inline in the handler.',
    backendRisks:
      'Inline check runs delay the 2xx to GitHub (causing retries) and risk duplicate runs on re-delivery.',
    conceptsUsedSlugs: ['webhooks', 'rest-api-design', 'api-validation'],
    conceptsToLearnSlugs: ['idempotency', 'queues', 'retry-strategy'],
    architectureNotes:
      'Verify + dedupe by delivery id, enqueue, return fast 2xx; run attestation idempotently per (pr, head_sha).',
    improvementIdeas: 'Add a queue; dedupe by delivery id and head_sha; retries + DLQ for status posts.',
    nextBackendAction: 'Make the webhook handler return 2xx fast and process attestations async.',
    relatedDecisionGuideSlugs: ['webhooks-vs-polling', 'how-to-handle-retries'],
    relatedCaseStudySlug: 'mergeattest-pr-review',
  },
  {
    slug: 'aegisrail',
    projectName: 'AegisRail',
    projectType: 'aegisrail',
    status: 'paused',
    description: 'Guardrails / safety tooling project (early stage).',
    currentArchitecture: 'Prototype Next.js app; architecture not yet settled.',
    backendRisks: 'Unclear data model and trust boundaries; security requirements not yet defined.',
    conceptsUsedSlugs: ['rest-api-design'],
    conceptsToLearnSlugs: ['authorization', 'security', 'audit-logs', 'observability'],
    architectureNotes: 'Define trust boundaries and authz model before building features.',
    improvementIdeas: 'Start with a clear data model and deny-by-default authorization.',
    nextBackendAction: 'Write down the threat model and core entities.',
    relatedDecisionGuideSlugs: ['how-to-design-multi-tenancy'],
  },
  {
    slug: 'podcut',
    projectName: 'PodCut',
    projectType: 'podcut',
    status: 'active',
    description: 'Podcast/audio processing tool with uploads and async processing.',
    currentArchitecture:
      'Next.js + Neon + R2. Audio uploaded via the app; processing kicked off in the request.',
    backendRisks:
      'Large uploads and processing in the request path hit serverless time/size limits.',
    conceptsUsedSlugs: ['file-storage', 'object-storage', 'serverless-functions'],
    conceptsToLearnSlugs: ['queues', 'background-jobs', 'cold-starts'],
    architectureNotes:
      'Direct-to-R2 presigned uploads; enqueue processing; worker handles transcoding with retries.',
    improvementIdeas: 'Presigned uploads; queued processing; progress updates.',
    nextBackendAction: 'Switch to presigned R2 uploads and queue the processing step.',
    relatedDecisionGuideSlugs: ['do-i-need-a-queue', 'serverless-vs-long-running-server'],
  },
  {
    slug: 'eastbase',
    projectName: 'Eastbase Studio',
    projectType: 'eastbase',
    status: 'active',
    description: 'Studio/agency umbrella for multiple small SaaS products.',
    currentArchitecture: 'Several Next.js + Neon apps sharing patterns but not infrastructure.',
    backendRisks: 'Inconsistent backend conventions across products (errors, auth, multi-tenancy).',
    conceptsUsedSlugs: ['rest-api-design', 'api-error-handling', 'authentication'],
    conceptsToLearnSlugs: ['multi-tenancy', 'modular-monolith', 'observability'],
    architectureNotes:
      'Standardize a starter: error envelope, auth, tenant isolation, logging — reuse across products.',
    improvementIdeas: 'Build the multi-tenant SaaS starter as the shared baseline.',
    nextBackendAction: 'Codify a shared backend starter from the multi-tenant case study.',
    relatedDecisionGuideSlugs: ['monolith-vs-modular-vs-microservices', 'how-to-handle-api-errors'],
    relatedCaseStudySlug: 'multi-tenant-saas-starter',
  },
  {
    slug: 'costtracker',
    projectName: 'CostTracker',
    projectType: 'internal-tool',
    status: 'active',
    description: 'Internal expense/budget tracker.',
    currentArchitecture: 'Simple Next.js + Neon CRUD app.',
    backendRisks: 'Money math correctness; missing audit trail.',
    conceptsUsedSlugs: ['rest-api-design', 'transactions', 'layered-architecture'],
    conceptsToLearnSlugs: ['audit-logs', 'backups'],
    architectureNotes: 'Keep it deliberately simple; integer cents; add an audit log.',
    improvementIdeas: 'Add audit logging and verified backups; nothing fancier.',
    nextBackendAction: 'Add an append-only audit log for edits.',
    relatedDecisionGuideSlugs: ['soft-delete-vs-hard-delete'],
    relatedCaseStudySlug: 'costtracker-finance',
  },
  {
    slug: 'envvault',
    projectName: 'EnvVault',
    projectType: 'other',
    status: 'active',
    description: 'Encrypted environment-variable manager.',
    currentArchitecture: 'Next.js + Neon prototype; secrets currently stored without envelope encryption.',
    backendRisks:
      'Secrets at rest, leakage via logs/errors, and tenant isolation are the whole product — and not yet hardened.',
    conceptsUsedSlugs: ['authentication', 'authorization', 'multi-tenancy'],
    conceptsToLearnSlugs: ['security', 'audit-logs'],
    architectureNotes:
      'Envelope encryption (KMS master key → per-secret data keys); deny-by-default authz; append-only access log; taint secrets.',
    improvementIdeas: 'Implement envelope encryption and a tamper-evident access log.',
    nextBackendAction: 'Design and implement envelope encryption for secrets at rest.',
    relatedDecisionGuideSlugs: ['how-to-design-multi-tenancy'],
    relatedCaseStudySlug: 'envvault-env-manager',
  },
  {
    slug: 'vocabulary-tracker',
    projectName: 'Vocabulary Tracker',
    projectType: 'other',
    status: 'paused',
    description: 'Personal spaced-repetition vocabulary app.',
    currentArchitecture: 'Small Next.js + Neon app with a basic review schedule.',
    backendRisks: 'Scheduling correctness; little else at this scale.',
    conceptsUsedSlugs: ['rest-api-design', 'pagination'],
    conceptsToLearnSlugs: ['transactions'],
    architectureNotes: 'Reuse an SM-2 scheduler; keep everything simple.',
    improvementIdeas: 'Borrow the Review Center’s scheduler logic directly.',
    nextBackendAction: 'Port the SM-2 scheduling into the app.',
    relatedDecisionGuideSlugs: [],
    relatedCaseStudySlug: 'vocabulary-learning-tracker',
  },
];
